version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.21.2
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformer:8080'
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      - t2v-transformer

  t2v-transformer:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'

  neo4j:
    image: neo4j:5.11.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/your_password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

  rag-server:
    build:
      context: .
      dockerfile: Dockerfile.rag
    ports:
      - "8001:8001"
    environment:
      WEAVIATE_URL: http://weaviate:8080
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
      VECTOR_DB_PATH: /app/data/chroma_db
    volumes:
      - ./data:/app/data
    depends_on:
      - weaviate

  graphrag-server:
    build:
      context: .
      dockerfile: Dockerfile.graphrag
    ports:
      - "8002:8002"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: your_password
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - ./data:/app/data
    depends_on:
      - neo4j

volumes:
  weaviate_data:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins: 