[build]
builder = "nixpacks"

[deploy]
startCommand = "python smart_mcp_server.py --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PYTHONPATH = "."
PYTHONUNBUFFERED = "1"

# Required environment variables (set in Railway dashboard)
# DATABASE_URL = "postgresql://..."  # Supabase connection string
# OPENAI_API_KEY = "sk-..."
# SUPABASE_URL = "https://..."
# SUPABASE_KEY = "..."
# JWT_SECRET_KEY = "your-secret-key"
# REDIS_URL = "redis://..."  # Railway Redis addon