apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-data-pvc
  namespace: mcp-server
  labels:
    app: mcp-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard