apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
  namespace: mcp-server
  labels:
    app: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
  - name: http-api
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: mcp-protocol
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: mcp-server
  labels:
    app: nginx-loadbalancer
spec:
  selector:
    app: nginx-loadbalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: mcp
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
---
# Headless service for StatefulSet if needed
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-headless
  namespace: mcp-server
  labels:
    app: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
  - name: http-api
    port: 3000
    targetPort: 3000
  - name: mcp-protocol
    port: 8000
    targetPort: 8000
  clusterIP: None