version: '3.8'

services:
  mcp-staging:
    image: isa-mcp-staging:latest
    container_name: mcp-staging-test
    platform: linux/amd64

    ports:
      - "8081:8081"

    environment:
      # System
      - ENV=staging
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=true

      # Service Discovery (Consul will discover all services)
      - CONSUL_ENABLED=${CONSUL_ENABLED:-true}
      - CONSUL_HOST=${CONSUL_HOST:-staging-consul}
      - CONSUL_PORT=${CONSUL_PORT:-8500}

      # Database - Supabase
      - SUPABASE_LOCAL_URL=${SUPABASE_LOCAL_URL:-http://host.docker.internal:54321}
      - SUPABASE_LOCAL_ANON_KEY=${SUPABASE_LOCAL_ANON_KEY}
      - SUPABASE_LOCAL_SERVICE_ROLE_KEY=${SUPABASE_LOCAL_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_SCHEMA=${DB_SCHEMA:-dev}

      # Database - Neo4j
      - NEO4J_URI=${NEO4J_URI:-bolt://host.docker.internal:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}

      # External API Keys
      - COMPOSIO_API_KEY=${COMPOSIO_API_KEY}
      - BRAVE_TOKEN=${BRAVE_TOKEN}

      # MCP Service
      - MCP_PORT=8081
      - MCP_API_KEY=${MCP_API_KEY}
      - REQUIRE_MCP_AUTH=${REQUIRE_MCP_AUTH:-true}

      # Performance Optimization
      - LAZY_LOAD_AI_SELECTORS=${LAZY_LOAD_AI_SELECTORS:-true}
      - LAZY_LOAD_EXTERNAL_SERVICES=${LAZY_LOAD_EXTERNAL_SERVICES:-true}

      # Composio Cache
      - COMPOSIO_CACHE_DIR=/app/cache

      # Hardware SDK
      - HARDWARE_AUTO_SCAN=false

    volumes:
      # Mount source code for development
      - ../../core:/app/core:ro
      - ../../tools:/app/tools:ro
      - ../../prompts:/app/prompts:ro
      - ../../resources:/app/resources:ro
      - ../../config:/app/config:ro

      # Persistent cache directory
      - mcp_cache:/app/cache

      # Logs directory
      - mcp_logs:/app/logs

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - staging_staging-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    restart: unless-stopped

volumes:
  mcp_cache:
    driver: local
  mcp_logs:
    driver: local

networks:
  staging_staging-network:
    external: true
