#!/bin/bash

echo "🧪 手动测试 Stripe Webhook"
echo "=========================="

echo "📋 使用这个流程测试webhook："
echo ""
echo "1. 在一个终端窗口运行："
echo "   stripe listen --forward-to localhost:8100/api/v1/webhooks/stripe"
echo ""
echo "2. 复制显示的 webhook signing secret 到 deployment/dev/.env.user_service"
echo ""
echo "3. 在另一个终端窗口运行以下命令触发事件："
echo ""
echo "🎯 测试订阅完成事件："
echo "stripe trigger checkout.session.completed"
echo ""
echo "🎯 测试订阅更新事件："
echo "stripe trigger customer.subscription.updated" 
echo ""
echo "🎯 测试支付成功事件："
echo "stripe trigger invoice.payment_succeeded"
echo ""
echo "📋 检查结果："
echo "• 查看Stripe CLI输出的事件转发日志"
echo "• 查看后端服务日志: tail -f logs/user_service.log"
echo "• 检查用户状态是否从 'free' 更新为 'pro'"
echo ""
echo "🔧 当前配置："
echo "• Webhook URL: localhost:8100/api/v1/webhooks/stripe"
echo "• Webhook Secret: $(grep STRIPE_WEBHOOK_SECRET deployment/dev/.env.user_service | cut -d'=' -f2)"
echo "• 目标用户: google-oauth2|107896640181181053492"